inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - "db/schema.rb"

Metrics:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

  Style/ClassAndModuleChildren:
  Exclude:
    - 'config/application.rb'